### ISSUE TITLE
battery state

### ISSUE THREAD

**Issue by h4nc** [ycardon/gigaset-elements-proxy#14]
I don't know where else I shoudl put this, so I open up an issue.

@ycardon could you tell us a bit more about the new battery state service. 

I think when I integrate one of those into home assistant as a sensor it will stay unknown until the battery state gets critical. Is that right?

Also when this sensor gets the critical state some time in future, will it automatically go to some "default" state after changing the battery? 

Nicest way would be to be able to integrate it as binary sensors (with device set as battery), but this way the proxy has to send a default and a critical state.

Thanks,
Hans

**Comment by ycardon** [comment]
I was not really sure what to do with the battery events... either send it a a "mysensor_battery" topic, "battery_critical" value  (as it is now) or send it to a "battery_critical" topic with the sensor name as value.

Or maybe it's not really interesting to follow this event at all: the status of the battery appears in the /basestations API, and I can make easier to use inside HA using the /sensors API.

**Comment by ycardon** [comment]
committed a version with /sensors showing the battery state when applicable

**Comment by h4nc** [comment]
Hi, 

I updated to the newest version 2.0.0 and now my gigasetproxy stopped working.

I get this:

```
Apr 24 18:23:56 raspberrypi systemd[1]: gigaset-server@pi.service: Unit entered failed state.
Apr 24 18:23:56 raspberrypi systemd[1]: gigaset-server@pi.service: Failed with result 'exit-code'.
Apr 24 18:24:06 raspberrypi systemd[1]: gigaset-server@pi.service: Service hold-off time over, scheduling restart.
Apr 24 18:24:06 raspberrypi systemd[1]: Stopped GigasetElements Server (local proxy to gigaset APIs).
Apr 24 18:24:06 raspberrypi systemd[1]: Started GigasetElements Server (local proxy to gigaset APIs).
Apr 24 18:24:23 raspberrypi node[548]: module.js:549
Apr 24 18:24:23 raspberrypi node[548]:     throw err;
Apr 24 18:24:23 raspberrypi systemd[1]: gigaset-server@pi.service: Main process exited, code=exited, status=1/FAILURE
Apr 24 18:24:23 raspberrypi systemd[1]: gigaset-server@pi.service: Unit entered failed state.
```

**Comment by ycardon** [comment]
Sorry for that :'(

Have you installed the dependants libraries `> npm install` ?
What is your node version `> node --version` ? Can you upgrade it ?

This looks like that issue: https://github.com/nodejs/help/issues/1271

**Comment by h4nc** [comment]
had node version v8.11.1

I tried your bullet points. Unfortunately I used both commands (hopefully I did not brake it with the -- force command):

```
pi@raspberrypi:~ $ npm cache clean --force
(node:636) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm WARN using --force I sure hope you know what you are doing.
```

This is what I get when I enter 

```
pi@raspberrypi:~ $ npm install
(node:654) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Linux 4.14.98+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! path /home/pi/package.json
npm ERR! syscall open
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0
```

**Comment by ycardon** [comment]
1. you should upgrade to a newer version of node.
1. then go to your gigaset-proxy install and delete the node_module directory `> rm -fr node_module`
1. then install all dependancies `> npm install`
1. then launch the gigaset-proxy by hand `> node app.js` to get all possible error messages

**Comment by h4nc** [comment]
> you should upgrade to a newer version of node.

What is the right command for that.

npm install -g npm@latest

doesnt work, I get a lot of errors like above.

**Comment by h4nc** [comment]
Ok, so installed a new version of node with:

https://stackoverflow.com/questions/8191459/how-do-i-update-node-js

```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

`node --version` gives `v10.15.3` now

but when I intall npm with `npm install` I still get the error from above, and in that error it tells me that the node version is still 8.11.1

```
(node:14710) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.98+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/gigaset-elements-proxy
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/gigaset-elements-proxy/npm-debug.log
npm ERR! not ok code 0
```

Don't know what to do.

**Comment by h4nc** [comment]
Can you give me another hint how to fix this?

I have a backup and can go back.
But I would prefer following your newest versions.

**Comment by h4nc** [comment]
I don't understand why it tells me it installed a newer version during the install, but when I look for the installed version is still shows the old one.

```
pi@raspberrypi:~ $ sudo n stable

     install : node-v10.15.3
       mkdir : /usr/local/n/versions/node/10.15.3
       fetch : https://nodejs.org/dist/v10.15.3/node-v10.15.3-linux-armv6l.tar.gz
######################################################################## 100,0%
   installed : v10.15.3

pi@raspberrypi:~ $ node --version
v8.11.1
```

**Comment by ycardon** [comment]
Seems that you are using the [`n`](https://github.com/tj/n) utility to manage node versions. 
I don't use it but it seems that you have to run it again to choose your version `sudo n`

![](https://camo.githubusercontent.com/e3c6ac1ad2a69e2e969597b69d794658cb64df88/687474703a2f2f6e696d69742e696f2f696d616765732f6e2f6e2e676966)

**Comment by h4nc** [comment]
To be honest I thought n is a abbreviation for npm.

I wanted to fix it somehow to I tried different things on how to update node.

This example with n was one of them.


In my last try I tried to update npm and afterwards node.

So I think my command to update node has to include npm instead of n to update it.

**Comment by h4nc** [comment]
Is it possible to upgrade node with npm? if yes how would the command look like?

**Comment by ycardon** [comment]
Sorry, I wasn't that helpful...

Yes this might be the only visible 'improvement' I did in moving to version 2.0. Most of the work was under the hood: moving to typescript really helps to catch more bugs before they happens. I was really needing that because you and @sracing are using sensors I don't own so I can't test what I'm writing. Typescript adds more safety nets.

Well, just tell me if adding the battery state in the /sensors API if sufficient for you to close the issue.

**Comment by h4nc** [comment]
> Well, just tell me if adding the battery state in the /sensors API if sufficient for you to close the issue.

It is. But one more question. 
Which stated are there for battery. Do you know that?

"ok", ...

**Comment by h4nc** [comment]
This is the binary sensor I use now to watch the battery state:


```
- platform: rest
  name: gigaset_yoursensor_battery
  friendly_name: "YourSensor"
  scan_interval: '15'
  resource: http://ipadress:3000/sensors
  value_template: "{{ value_json[0].name == 'YourSensor' and value_json[0].battery != 'ok' }}"
  device_class: battery
```

You could add it to the example section.

I'm not a 100% sure if this
{{ value_json[0].name == 'YourSensor' and value_json[0].battery != 'ok' }}

points to the right information. I don't know if this way it only picks the data of YourSensor and not a battery state from a different sensor to.
Also this should poll every few sec's.

**Comment by ycardon** [comment]
I'm not that good in HA templates, but that expression seems to return `true` if the first `[0]` sensor name is YourSensor and the first `[0]` sensor battery is ok.

If I'm right, this is not what we want.

**Comment by Petro31** [comment]
What info are you trying to get out of the sensor?  Also, what type of rest sensor is this?  Binary_sensor or sensor?

**Comment by h4nc** [comment]
Thanks for joining @Petro31 

> What info are you trying to get out of the sensor?
The battery state and what we get is a list like this one:
https://user-images.githubusercontent.com/25117255/56868835-2e3bfd00-69f8-11e9-9eea-aae5c9fc30d9.png

There are more devices in that list, currently I'm not at home, but maybe someone else @ycardon or @sracing es able to provide the full output of /sensors

So there are serveral devices in that list and I want to use a **binary** restful sensor for each of that list. So I thing the sensor has to look for a certain device and the battery state. This is what I tried to do.

**Comment by Petro31** [comment]
Yes, I understand that.  What value do you want to get for your battery state?  A number?  A On/OFF?  The word 'ok'?

**Comment by h4nc** [comment]
Yes, I want a binary sensor.

The thing is I (we?) do not know which other states are provide. I only saw the value 'ok' yet. 
so I don't know if there is only 'ok' and something like 'not_ok'.

So you can confirm that the code above is able to look for the different devices?
Those sensors are "normal" when the battery value is ok and should go "low" (or something like that) when the value changes from ok. Right?

```
- platform: rest
  name: gigaset_yoursensor1_battery
  scan_interval: '300' #seconds
  resource: http://ipadress:3000/sensors
  value_template: "{{ value_json[0].name == 'YourSensor1' and value_json[0].battery != 'ok' }}"
  device_class: battery

- platform: rest
  name: gigaset_yoursensor2_battery
  scan_interval: '300' #seconds
  resource: http://ipadress:3000/sensors
  value_template: "{{ value_json[0].name == 'YourSensor2' and value_json[0].battery != 'ok' }}"
  device_class: battery
```

**Comment by Petro31** [comment]
Sorry, I can't help.  Information appears to come directly from the device/web call.

**Comment by h4nc** [comment]
Ok thanks. Maybe @ycardon is able explain the issue better.

**Comment by ycardon** [comment]
or maybe not... sorry.

I've added a new API in v2.1 that might help the handling from HA. If you hit `sensors/<my_sensor_friendly_name>` then you will get that specific sensor status.

**Comment by h4nc** [comment]
Ok, so with the new possibility the code can look like this now:

in binary_sensor.yaml
```
- platform: rest
  name: gigaset_YOURSENSOR_battery
  scan_interval: '300'
  resource: http://YOUR_IP:3000/sensors/YOURSENSOR
  value_template: "{{ value_json[0].battery != 'ok' }}"
  device_class: battery
```

> I'm not that good in HA templates, but that expression seems to return true if the first [0] sensor name is YourSensor and the first [0] sensor battery is ok.

@ycardon I understand that with the new possibilty /sensor/friendly_name this isn't important any more, but I still like to now if your guess above is true. 
So does is only look for the first battery value in the list.
I thought with the code above ( ... and ...) I first select the sensor and than look at the battery state. 
I think you get what I mean. @petro31 was involved and is an absolute ha pro, but I don't know if I explained everything good enough, so that he was able to spread his knowledge.

**Comment by ycardon** [comment]
I wasn't sure about `value_json[0].battery`but you've changed it to `value_json.battery` (the `/sensors` URL is returning an array, `[0]` is extracting the first object of the array)

**Comment by ycardon** [comment]
@Petro31, we are receiving a JSON message from an API in the form of:
```js
[
  {
    "name": "deviceA",
    "battery": "ok"
  },
  {
    "name": "deviceB",
    "battery": "critical"
  }
]
```
We'd like to extract sensors for each device with associated battery state. Is there a simple way to do it with the templating engine, preferably without calling the API multiple times.

**Comment by ycardon** [comment]
FYI @h4nc, I've changed the `sensors/` API response in v2.1.2. It should be easier to deal within HA.

It's now in the form:
```js
{
  deviceA: {
    "name": "deviceA",
    "battery": "ok"
  },
  deviceB: {
    "name": "deviceB",
    "battery": "critical"
  }
}
```

Now you can access any property of any sensor directly. For instance:
```
value_template: "{{ value_json.deviceA.battery != 'ok' }}"
```

**Comment by h4nc** [comment]
Thanks for letting me know. 

So now there are at least two options the pull the battery state.

The new one with /sensors/friendly_name

and

the new new one you showed in your last posting.

Both leads to the same, right? Is there one path that I should prefere? 
Maybe you plan to remove the /sensors/friendly_name again (because it's could be seen as redundant) in a future update?

**Comment by ycardon** [comment]
> Both leads to the same, right?

Both are the same functionally and they share the same code (and I'll keep both versions, use the one you prefer :) Maybe the first one (`sensor/`) is better because you can define only one rest sensor and add templates sensors based on this one (like in [this example](https://www.home-assistant.io/components/rest/#fetch-multiple-json-values-and-present-them-as-attributes)): that will lead to less calls to the Gigaset API.

> In your example you mentioned "ok" and "critical"

Yes one of my battery shows "critical", I don't know if there are other states, for safety you should keep your "not ok" test.

> What do you think about adding the versionnumber to the header of the proxy.

What do you call the header ? For now you have the version number in the logs when the server starts.

> Also I noticed that the version number isn't shown any more when I hit `systemctl status gigaset-server@pisystemctl`

I didn't know about that... no idea why it was there and why it's gone :)

**Comment by h4nc** [comment]
> that will lead to less calls to the Gigaset API.

thanks I will follow your advice.

> What do you call the header ? For now you have the version number in the logs when the server starts.
> 
> I didn't know about that... no idea why it was there and why it's gone :)

Sry for being too unspecific. With "header" I mean the first line of the proxy webpage.

About the logs: I maybe just missed the first lines of the logs. So the version number is most probably still there. Forget about that.

**Comment by h4nc** [comment]
About your suggestion here:

> Maybe the first one (sensor/) is better because you can define only one rest sensor and add templates sensors based on this one (like in this example): that will lead to less calls to the Gigaset API.

I don't know if that's really possible. I think there is a limitation on how many characters a attribute or state can have. I think 255 characters. If that's true we will run into new issues with that.

**Comment by ycardon** [comment]
Now (in v2.1.3) we have a version number in the README.md (and the proxy webpage, which is the same) and a better build system to automate that.

About having 1 rest sensor and n templates: if you try it, please give me feedbacks.

**Comment by h4nc** [comment]
> Now (in v2.1.3) we have a version number in the README.md (and the proxy webpage, which is the same) and a better build system to automate that.

Thanks for your effort. Nice to have it at the top of the Readme-file.
It think in former versions I saw the version number in the logs (see the picture). It looks like it is gone (this is what I meant in one of my last posts). I don't mind that it's gone (if it's really gone), because we have it in the readme now. 

<img width="852" alt="Bildschirmfoto 2019-05-06 um 12 50 04" src="https://user-images.githubusercontent.com/25117255/57221116-2f73b800-6ffe-11e9-81ba-1edf79a40c3c.png">

> About having 1 rest sensor and n templates: if you try it, please give me feedbacks.
Sure I will test it, but before it would be nice to here what @Petro31 thinks about this (regarding the character limitation).

**Comment by ycardon** [comment]
Version number is on a previous line in the logs
```
2|gigaset  | [Mon May 06 2019 20:41:08] [INFO]   gigaset-element-provy 2.1.3 is starting
2|gigaset  | [Mon May 06 2019 20:41:08] [INFO]   authorize on gigaset cloud api : starting
2|gigaset  | [Mon May 06 2019 20:41:08] [INFO]   mqtt connected
```
(and there is a typo: provy > proxy :)

But as you suggested, we can now see it on the landing page.

**Comment by h4nc** [comment]
We should totally call it gigaset provy from now on ;)

Strange that it doesn’t show me the line before that one. Have to give it another try.

**Comment by h4nc** [comment]
> Have to give it another try.
It still shows the version number in the logs, so thats fine

@ycardon I currently have a window sensor that reports "fast leer" (="almost empty") as battery state within the gigaset App

But the value in the proxy sensor page still is "ok". I restartet and refreshed the proxy but no change, still "ok".

**Comment by ycardon** [comment]
Strange... could you please check the 'basestations/' page, witch is the RAW Gigaset output ?

**Comment by h4nc** [comment]
It also says "ok" there.

```
...
"battery": {
  "state": "ok"
...
```

To make sure I don't check the wrong sensor, I looked at all battery states in the 'basestations/' page.
All states are "ok".

Maybe "almost empty" is still "ok" and the next state (something like) "empty" will report "critical" in the proxy?

**Comment by ycardon** [comment]
seems like so...

**Comment by h4nc** [comment]
Ok, I‘ll wait for the next state and come back.

**Comment by h4nc** [comment]
Hi,

the state went to "critical". Now I can see it in ha, so it works fine!
