### ISSUE TITLE
Wiki: dead link to gigaset api

### ISSUE THREAD

**Issue by Pe-MaKer** [ycardon/gigaset-elements-proxy#18]
The link to the Gigaset api on the readme.md is dead.

One of my fellows at Gigaset gave me this link to their API definitions:
https://api.gigaset-elements.com/app-mids-open-api/swagger-ui.html

**Comment by ycardon** [comment]
1. Many thanks for the link to the Swagger spec. It seems this API is different from the one I use. I'll take some time to test it.

2. What link on the readme.md is dead ? The ones on the `raw Gigaset APIs` paragraph ?
(Note that if you're reading this page on github, theses links does not work: you have to install the project)

**Comment by Pe-MaKer** [comment]
1. Great if this API link is helpful in any way. I've asked them for any locally accessible API of the Gigaset Base. Waiting for a reply but I'm pretty sure they will not open anything locally for security reasons. It would be so cool to keep everything in my network instead of using their cloud API.

2. The link to Gigaset.fr seems to be okay. I only expected a link to the API description and not a link to the product page.
Everything's fine.
