### ISSUE TITLE
Auto boot

### ISSUE THREAD

**Issue by h4nc** [ycardon/gigaset-elements-proxy#2]
Sorry another question that might be closed fast.

Will the tool autoboot or do I have to use something like crontab? Any other suggestions for noobs?

**Comment by ycardon** [comment]
No problem, I'm glad to help,

That will depend on your OS, if you run on a systemd enabled OS (ubuntu, raspbian, arch...) you can write a custom [unit file](https://wiki.archlinux.org/index.php/Systemd#Writing_unit_files), it works for anything.

If you want a more node.js-ecosystem-friendly solution, you can use a process manager ([PM2](http://pm2.keymetrics.io) for instance is very simple to use and support different OSes.

**Comment by h4nc** [comment]
My OS is raspbian stretch lite. 

Thanks for your advice, but its hard for me to find out which is the right command to use. 

How does it work. I create a file in this section: /etc/systemd/system/unit.d/
which starts the your tool with "node app.js" ?

**Comment by ycardon** [comment]
Ah, you choose the systemd solution: it's a little trickier than PM2 but it's a useful tool to know as it's the standard way to start services under raspbian.

Yes you create a file ``/etc/systemd/system/gigaset-server@myuser.service`` the @myuser is used in the service definition to tell it has to be run with this user rights. Content will be:

```
[Unit]
Description=GigasetElements Server (local proxy to gigaset APIs)
After=network.target

[Service]
Type=simple
User=%i
WorkingDirectory=/home/myuser/bin/gigaset
ExecStart=/usr/bin/node app.js
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```

Then you will have to start the service ``sudo systemctl start gigaset-server@myuser.service`` and also enable it so that it starts on next reboot ``sudo systemctl enable gigaset-server@myuser.service``.

I advise you to start / enable the service only once the solution is working.

**Comment by ycardon** [comment]
added these information about setting-up a systemd service in the ``examples`` directory

**Comment by h4nc** [comment]
I tried this now, but unfortunately it seems like the service does not auto start.

I'd like to have this because of power cuts. So if there is a power cut and my pi zero w boots after this again, it would be preferable not to start something manually again. 

But after a plug in plug out, no mqtt events and no server (myserver...)

**Comment by h4nc** [comment]
this journalctl -fu gigaset-server@myuser returns this:
Okt 25 16:47:14 raspberrypi systemd[1521]: gigaset-server@myuser.service: Failed at step USER spawning /usr/bin/node: No such process
Okt 25 16:47:14 raspberrypi systemd[1]: gigaset-server@myuser.service: Main process exited, code=exited, status=217/USER
Okt 25 16:47:14 raspberrypi systemd[1]: gigaset-server@myuser.service: Unit entered failed state.
Okt 25 16:47:14 raspberrypi systemd[1]: gigaset-server@myuser.service: Failed with result 'exit-code'.
Okt 25 16:47:24 raspberrypi systemd[1]: gigaset-server@myuser.service: Service hold-off time over, scheduling restart.
Okt 25 16:47:24 raspberrypi systemd[1]: Stopped GigasetElements Server (local proxy to gigaset APIs).
Okt 25 16:47:24 raspberrypi systemd[1]: Started GigasetElements Server (local proxy to gigaset APIs).

and repeats every few seconds.

systemctl status gigaset-server@myuser
returns:
● gigaset-server@myuser.service - GigasetElements Server (local proxy to gigaset APIs)
   Loaded: loaded (/etc/systemd/system/gigaset-server@myuser.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2018-10-25 16:48:26 CEST; 9s ago
  Process: 1542 ExecStart=/usr/bin/node app.js (code=exited, status=217/USER)
 Main PID: 1542 (code=exited, status=217/USER)

Okt 25 16:48:26 raspberrypi systemd[1]: gigaset-server@myuser.service: Failed with result 'exit-code'

**Comment by h4nc** [comment]
I have it running on stretch lite. I installed and configured using ssh. 

It seems like after closing a remote ssh session from my mac the server immediately stops.
What could cause this? Is it a user login issue and how could I solve this?

**Comment by ycardon** [comment]
Well the error message you had seems pretty meaningful: ``/usr/bin/node: No such process``. It appears that your ``node`` binary is not located under ``/usr/bin/node``.

You can see where it is installed by typing ``which node`` and change you script accordingly.

**Comment by h4nc** [comment]
Ok I will look that up tomorrow.

I‘m not sure about „@myuser“. Do I leave it like that or replace it with my user.
Myuser appears in the filename and in the file itself (working directory).

Also I‘m wondered about the working directory, because to start your tool I had to go to 
cd gigaset-elements-proxy
and than
node app.js 

In the script this seams different.

**Comment by ycardon** [comment]
You have to adapt the ``workingDirectory`` and replace ``myuser`` with ``pi``.

**Comment by h4nc** [comment]
I can confirm that it auto started now after a power cut, thanks!

I still like to disable/stop these wrong commands.

**Comment by ycardon** [comment]
I'd say ``sudo systemctl disable gigaset-server@myuser.service`` and then you delete the file.
