### ISSUE TITLE
502: Bad Gateway

### ISSUE THREAD

**Issue by Cavekeeper** [ycardon/gigaset-elements-proxy#24]
Installation on a fresh system.
Host: Raspbian GNU/Linux 10 (buster), Supervised installation on Raspberrypi_3.
Installed as Add-On: Gigaset-Elements proxy
Installation failed and Add-On can`t start.
Log:

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
ifelse: fatal: unable to exec /run.sh: Exec format error,
[cmd] /run.sh exited 126,
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] done.,
[s6-finish] waiting for services.,
[s6-finish] sending all processes the TERM signal.,

Wenn I open the web UI the error:

 `502: Bad Gateway` 

and a new system log appears:

`ERROR (MainThread) [hassio.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8094 ssl:None [Host is unreachable]`

7 container are running well without any errors.

**Comment by ycardon** [comment]
Ok right, I get the same error after having rebuild the addon... I saw many releases of add-ons recently: something must has changed in the addon config mechanism recently.

Thank's for the info, I will fix it ASAP (mine is also broken now :)

**Comment by ycardon** [comment]
It was simpler than I expected: Frenck introduced a new bashio base image, hence all the republish of addons... but I can still use the "old" way of starting script, witch is less forgiving in the new base image version. Just had to add a !#/bin/bash at the beginning of the run script to indicate it's ment to be run by bash.

There is a v1.3 of the addon, just force refresh the addon store, update to v1.3, rebuild and restart.
