### ISSUE TITLE
Status of gigaset base

### ISSUE THREAD

**Issue by h4nc** [ycardon/gigaset-elements-proxy#3]
Me again, with another question. Sorry.

Is there a way to track the status of the alarm system.
This would be really nice, because than you could notify family members that the alarm mode has been set automatic.

There are 4 modes (i can only tell the german modes, because my app is german):

- Zu Hause (at home)
- Ausser Haus (away)
- Nacht (night)
- Individuell (individual)

First one could be "false", the rest "true".

An home assistant automation could be triggered if Status changes to true. Condition only between XX:XX and XX:XX. Action: notification.

**Comment by ycardon** [comment]
Yes, good idea: 
- I don't know if a status change in the alarm system launches an event on the Gigaset API. I'll do some test but tell me if you see one
- if not, it is possible to implement this directly inside home-assistant using a REST template to extract the state (this project includes a web api exposing the Gigaset API, for states that would be http://myserver:3000/api/v1/me/basestations) and add an automation when this state changes

**Comment by ycardon** [comment]
I've added a new API: /intrusion_settings that returns the selected alarm mode, it should be easier to use inside HA than a restful sensor.

**Comment by h4nc** [comment]
I thought I can use sour new API with the scrape sensor, but unfortunatly I don't know how to read the "whole" webpage. Because it need to "select" something. 

https://www.home-assistant.io/components/sensor.scrape/

I tried this:

```
sensor:
  - platform: scrape
    name: Gigaset Status
    resource: http://myserver:3000/intrusion_settings
    select: ""
```

select
(string)(Required)Defines the HTML tag to search for. Check Beautifulsoup’s CSS selectors for details.

**Comment by h4nc** [comment]
Is there a chance to use this new api again to publish mqtt events?

It would be great to use it like that

home = false
away, night and individual = true

Using mqtt for this would be better than using a sensor which has to look after the status every few seconds.

**Comment by ycardon** [comment]
As I've said, I don't know if a status change in the alarm system launches an event on the Gigaset API. Tell me if you see one.

**Comment by h4nc** [comment]
Yes, it launches events. I can see them in 
myserver:3000/api/v2/me/events 

They look like this:
Every changs seems to launch two events

{"events":[{"id":"4182f7cf76f3a5d","state":"ok","ts":"1540","type":"isl01.bs01.intrusion_mode_loaded","o":{"friendly_name":"Zuha","modeBefore":"away","cre_uid":"318","modeAfter":"home","userId":"https://im.gigaset-elements.de/identity/api/v1/openid/identifier/id/d5896bbac8","status":"success"},"source_id":"B6B9021D8","source_type":"bs01","state_pre":"ok"},{"id":"5c9478a0a0","state":"ok","ts":"154","type":"isl01.configuration_changed.user.intrusion_mode","o":{"modeBefore":"away","modeAfter":"home"},"source_id":"app-services-intrusion-detector@dkrd1.reef","source_type":"isl01","state_pre":"ok"},

I changed those id values, as i don’t know if it is sensible to publish these values here.

**Comment by ycardon** [comment]
I've pushed a new version, it should be easier to tell (and modify) how gigaset events are mapped to mqtt. @h4nc can you do the testing and eventually modify it ?

https://github.com/ycardon/gigaset-elements-proxy/blob/fd13e4a358c3aa18ddea930d79ba1bed9c4c284c/app.js#L40-L59

**Comment by h4nc** [comment]
Yes, I‘ll do the testing.

Which will be the mqtt topic for the Status?

Is it the friendly name of the base?

**Comment by h4nc** [comment]
I already testet it and I get what you did, but listening to the base topic just returns true values, no matter to which alarm mode I switch.

 		case 'isl01.bs01.intrusion_mode_loaded': // changed security mode 
 			if (event.o.modeAfter == 'home') return 'false' 
 			else return 'true' 

I rechecked the case... it is the same. Switching to home should trigger a false event, but it doesn't.
Maybe wrong topic? I took the friendly name next to the intrusionmode case (which is the friendly name of the base)

**Comment by h4nc** [comment]
I testet your new version now, but I still only get true values.

I also treid to add 
`console.log ('security mode has changed')`
in line 53 but nothing changes.

Also it seems like the jsonview pluging doesn't work in my googe chrome browser (on a mac).
It is acitvated but does nothing with the webpage. But thats another problem.

**Comment by ycardon** [comment]
Ok I've found the problem: in the eventMapper() function, I was confusing event type and sensor type for this particular event.

It's working now in my system (I was not able to do tests with the last version)

**Comment by h4nc** [comment]
Works for me too. Great job, thank you.

I have another idea to make this project even better. I most probably will open another issue in the next time. Hopefully I don't bother you with all these comments. And sorry that I can only help with testing the code and not writing it.

**Comment by h4nc** [comment]
It was great to see if status is "home" (off) or something else (on) by mqtt.

Now I have a usecase where it would be better so see the actual stated dilivered by mqtt. 
So it would be better if its sends home, night, individual and away and not only off for home and on fpr the other three ones. 

The reason is I'd like to implement an occupancy mode for my lights and it would be useful to use the "away" state of gigaset for this. 
If its on nightmode I don't need the lights to switch on randomly.

so it it possible to deliver this information in one topic?

**Comment by h4nc** [comment]
Hi, 
I testet this and it looks like the state will only be reportet when i perform a "force refresh". Only this way I get a reliable state update (not on or off).
I think to avoid redundant information, we could use the state **instead** of sending true or false. To tell if gigaset is on or off a simple binary_sensor could tell if its on or off, but for this we would need reliables states (home, away...)

in binary_sensor.yaml:
```
- platform: template
  sensors:
    gigaset_status: 
      value_template: >-
        {{ is_state('sensor.gigaset_status', 'night') 
            or is_state('binary_sensor.wohnzimmer', 'away')
            or is_state('binary_sensor.0x00158d000232db0a', 'individual') }} 
```
better ideas are welcome, as this does not include "home" to be off, because this way also now value will be off.


Great idea to control the display inside HA, but as I watch my tv shows on an apple tv, my macbook is closed when something is running.

**Comment by ycardon** [comment]
Oups, sorry for that: I missed one change in the code. It should be ok now.
I will include your template in the example section.

**Comment by h4nc** [comment]
works now. 
My example above was faulty. I edited it. Could you please add it to the example section.

**Comment by h4nc** [comment]
So this is my example for the example section (I wanted to delet the post above because I mentioned an ID of one sensor accidentally, even if nobody can do something with it because its local, this should probably not be public)

in binary_sensor.yaml:

```
- platform: template
  sensors:
    gigaset_status: 
      value_template: >-
        {{ is_state('sensor.gigaset_status', 'night') 
            or is_state('sensor.gigaset_status', 'away')
            or is_state('sensor.gigaset_status', 'custom') }} 
```
in sensor.yaml

```
- platform: mqtt
  name: "Gigaset Status"
  state_topic: "gigaset/YOURBASENAME"
```
