### ISSUE TITLE
ws02 sensor, tilt = false should be true

### ISSUE THREAD

**Issue by h4nc** [ycardon/gigaset-elements-proxy#4]
Hi, 

so I tested everything again.

ps02 and ds02 work just fine.

But there is still one issue with the ws02. 
"tilt" returns a false value. So HA sees it as closed. bur you know a tilted window is open. 

so 
close has to be false
tilt has to be true
open has to be true

Again big thanks.

**Comment by ycardon** [comment]
oops, sorry... I'm changing that. I've pushed a new (new-new... :) version

**Comment by h4nc** [comment]
Great :D
