### ISSUE TITLE
create a hass.io add-on for this project

### ISSUE THREAD

**Issue by ycardon** [ycardon/gigaset-elements-proxy#6]
I don't have any hass.io setup, right now it's hard for me to create a hass.io add-on for this project but it should be quite easy:

following the hass.io [add-on documentation](https://developers.home-assistant.io/docs/en/hassio_addon_index.html)
- docker image could be inspired by ``node:10-alpine`` or [Node-RED](https://github.com/hassio-addons/addon-node-red/blob/master/node-red/Dockerfile) add-on
- pull npm package ``gigaset-elements-proxy``
- define a schema for configuration inside hass.io based on ``config/default.yaml``
- in the ``run.sh`` file, pass the configuration to the node config module using [NODE_CONFIG](https://github.com/lorenwest/node-config/wiki/Environment-Variables#node_config) environment variable

Contributions are welcomed :)

**Comment by Pe-MaKer** [comment]
A docker image for hass.io would be perfect!
A Node-RED add-on would be fine as well.

**Comment by ycardon** [comment]
there is now a hass.io add-on !

@Pe-MaKer, for the Node-RED add-on you only need to react to MQTT events.

**Comment by h4nc** [comment]
Awesome. Where can we find it?

**Comment by ycardon** [comment]
I've updated the README.md: the hassio repository is [here](https://github.com/ycardon/hassio-addons)

**Comment by h4nc** [comment]
This is great, can’t wait to test it. 

So this will be able to auto update right? This is really user friendly no more manual updates.

**Comment by ycardon** [comment]
yes, the addons gains out of the box cool HASSIO functionnalities such as auto update

**Comment by h4nc** [comment]
Thanks again for the addon. Works great and was very easy to setup.
 
I don't need more settings, but are you going to add settings about cameras and things like: `auth_interval: 10`. Or is it still there but now shown in the installed example.

Also I'd like to add some examples that might be useful for other uses. Maybe you want to add it in the example section.

in configuration.yaml
```
rest_command:
  gigaset_request:
    url: 'http://localhost:8094/force-refresh'
```

in sensor.yaml
```
- platform: rest 
  name: gigaset_health
  scan_interval: '15'
  resource: http://localhost:8094/api/v2/me/health
  value_template: '{{ value_json.system_health }}'
```

in binary_sensor.yaml:

```
- platform: rest
  name: gigaset_availability # Online/Offline
  scan_interval: '60' # 15
  resource: http://localhost:8094/api/v1/me/basestations
  value_template: "{{ value_json[0].status == 'online' }}"

#example for Kitchen 
- platform: rest
  name: gigaset_kitchen_battery
  scan_interval: '300' # sec
  resource: http://localhost:8094/sensors
  value_template: "{{ value_json.Kitchen.battery != 'ok' }}"
  device_class: battery
```

**Comment by ycardon** [comment]
Thank you for your suggestions: I will add theses templates to the example section (and I should have a proper readme file like any other addons)

Yes, all the settings are still there but I just wanted to keep the config as simple as possible in hassio. I could easily add them if needed (it is declared in [this file](https://github.com/ycardon/hassio-addons/blob/master/addon-gigaset/config.json), you can have a look, it's quite simple)

**Comment by h4nc** [comment]
Would be perfect if you could add that file to the add on description in future.

**Comment by h4nc** [comment]
BTW not important to
Me but it looks like this is missing in that file:

auth_interval

We had this in the other config file. But probably the standard setting is good as it is.

**Comment by ycardon** [comment]
I never had to change it :)

**Comment by ycardon** [comment]
I've committed your examples (but I will not change the addon version for that, don't worry if you don't see an auto-update proposal).

**Comment by h4nc** [comment]
BTW is there a certain reason why you changed the port?

**Comment by ycardon** [comment]
The 3000 port is on the list of the [well known ports](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers), as I was adding the hassio addon, I thought I could safely fix that point.
