### ISSUE TITLE
gigaset proxy server stopped working

### ISSUE THREAD

**Issue by h4nc** [ycardon/gigaset-elements-proxy#7]
Hi again,

my gigaset proxy server stopped working. I cannot open` http://myserver:3000` anymore.

Using `systemctl status gigaset-server@pi` I get the following error (see picture).

It looks like it is not able to autorize any more. Do you have the same issue?

<img width="832" alt="bildschirmfoto 2018-11-10 um 19 59 25" src="https://user-images.githubusercontent.com/25117255/48304976-5657a280-e523-11e8-877e-6d6ead89d0df.png">

**Comment by h4nc** [comment]
Found the issue. I recently updated to a new mosquitto version and accidentally reset my settings in mosquitto. 

I than choose to set "anonymus" to "false". 
I changed it to "true" now and it works again.

I don't get what this does. Looks like gigasetproxy is anonymus to the broker?
My Sonoff Devices worked with "false".

Do you know what this funktion does? Is it unsecure to use aktivate anonymus? Is the userlogin (+ pw) bypassed by this?

**Comment by ycardon** [comment]
Looking at the doc in mosquitto https://mosquitto.org/man/mosquitto-conf-5.html, then the allow_anonymous option allows mqtt client to connect without password.

If you want to set a login/password to mosquitto, you should also set it inside the gigaset-element-proxy config file. I haven't try, I do not enabled a password on my mqtt broker. Tell me if it's working (on not).

**Comment by h4nc** [comment]
>  Tell me if it's working (on not).
Yes it works. When anonymous is set false I can only connect with the right user and pw.

I don't know why it stopped working but rebooting the pi and my wifi router fixed the issue in the end.
